repos:
  # --- General hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        exclude: ^model_checkpoints/.*\.pth$

  # --- python_package hooks ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        # I = Import sorting (isort)
        # Others to optionally add: D for docstrings and UP for pyupgrade
        args: [ --fix, --select, I ]
      - id: ruff-format

# --- python type checking hooks ---
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        require_serial: true
        args: [ "--explicit-package-bases", "--ignore-missing-imports", "--implicit-optional"]
