[project]
name = "nrcan-wildfireriskmapping"
version = "0.1.0"
authors = [
    {name = "Hager Radi", email = "hager.radi@mila.quebec"},
    {name = "Tolu Olutayo", email = "toluwaleke.olutayo@mila.quebec"},
    {name = "Chirag Goel", email = "chirag.goel@mila.quebec"},
    {name = "Aldo Zaimi", email = "aldo.zaimi@mila.quebec"},
    {name = "Jana Osea", email = "jana.osea@mila.quebec"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "comet-ml>=3.55.0",
    "geopandas>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "pydantic>=2.12.5",
    "pytest>=9.0.1",
    "pyyaml>=6.0.3",
    "rasterio>=1.4.3",
    "scikit-learn>=1.7.2",
    "torch>=2.9.1",
    "torchmetrics>=1.8.2",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "xgboost>=3.3.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.14.5",
    "pytest>=8.1.1",
]

[tool.uv]
package = true

# Ruff config
[tool.ruff]
indent-width = 4
line-length = 140

[tool.ruff.lint]
select = [
    "E4",  # whitespace/formatting errors
    "E7",  # syntax issues
    "E9",  # runtime errors
    "F",   # pyflakes (unused imports, undefined vars)
    "I",   # import sorting
    "B",   # bugbear (best bug-prevention rules)
    "UP",  # pyupgrade
    "SIM", # simplify code
    "PT",  # pytest style checks
]
ignore = [
    "E203",  # compatible with Black-style formatting
    "B008",  # do not flag function argument default factory
]

# pytest config

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pre-commit>=4.5.0",
    "ruff>=0.14.5",
    "types-pyyaml>=6.0.12.20250915",
]
