#!/bin/bash
#SBATCH --job-name=grid_gen_dist_ign
#SBATCH --output=logs/array_%x_%A_%a.log
#SBATCH --array=0-53 # hard-coded since we know there's 54 hexel subdirs
#SBATCH --ntasks=1
#SBATCH --time=00:30:00
#SBATCH --mem=32G
#SBATCH --cpus-per-task=2

mkdir -p logs
source .venv/bin/activate

# Robust calculation of Num Tasks (Max Index - Min Index + 1)
TASK_ID=${SLURM_ARRAY_TASK_ID:-0}
# Default to 1 if not running in array
if [ -n "$SLURM_ARRAY_TASK_MAX" ]; then
    NUM_TASKS=$((SLURM_ARRAY_TASK_MAX - SLURM_ARRAY_TASK_MIN + 1))
else
    NUM_TASKS=1
fi

echo "Starting Worker $TASK_ID / $NUM_TASKS"

# ── Paths (override via env vars to run under a different account/environment) ──
# Scratch convention: <scratch_root>/<user-initial>/<user>.
SCRATCH_BASE=${SCRATCH_BASE:-/path/to/scratch/${USER:0:1}/${USER}/wildfireriskmapping/data_samples}
ROOT_DIR=${ROOT_DIR:-/path/to/raw_data/}
SAVE_DIR=${SAVE_DIR:-${SCRATCH_BASE}/data_samples_v2_full_support_dist_ignition}
SRC_DIR=${SRC_DIR:-${SCRATCH_BASE}/data_samples_v2_full_support}

# ── Copy shared index/tabular CSVs from the base data dir (task 0 only) ──────
# These files are not generated by the grid-gen script but are required by the
# training dataloader. We copy once from the reference dataset to avoid races.
if [ "$TASK_ID" -eq 0 ]; then
    mkdir -p "$SAVE_DIR"
    for f in train_indices.csv val_indices.csv test_indices.csv weather_table_processed.csv df_fire_fru_processed.csv target_log_stats.json; do
        if [ -f "$SRC_DIR/$f" ] && [ ! -f "$SAVE_DIR/$f" ]; then
            cp "$SRC_DIR/$f" "$SAVE_DIR/$f"
            echo "Copied shared CSV: $f"
        fi
    done
fi

# Generates data samples with 2-channel distribution-weighted ignition
# (ignition_grid_human + ignition_grid_lightning) instead of max-aggregation.
# Output dir: data_samples_v2_full_support_dist_ignition
python -m data_preparation.process_hexels_into_grids \
    --root_dir="$ROOT_DIR" \
    --save_dir="$SAVE_DIR" \
    --modelling_approach=1 \
    --win_h=256 \
    --win_w=256 \
    --overlap_ratio=0.2 \
    --ignition_weighting=distribution \
    --overwrite \
    --is_array_job \
    --task_id=$TASK_ID \
    --num_tasks=$NUM_TASKS
