extends: "../multi_output_spatial_weather.yaml"

save_dir: "experiments/context_models/unet_512_crop_256_no_firesize"

training:
  gradient_accumulation_steps: 8

data:
  root_dir: "/network/scratch/o/olutayot/nrcan_wildfireriskmapping/data_samples/data_samples_v4_context_512_crop_256"
  batch_size: 8
  num_workers: 4

logger:
  experiment_name: "unet_512_crop_256_no_firesize"
  tags:
    - "context_ablation"
    - "architecture=unet"
    - "input_patch=512"
    - "target_crop=256"
    - "target_stride=204"
    - "effective_batch=64"
    - "fire_size=none"

data_prep:
  win_h: 512
  win_w: 512
  target_crop_h: 256
  target_crop_w: 256
  overlap_ratio: 0.2
