extends: "mechanistic_propagation_v3_512_crop_256_spread_opportunity_q3.yaml"

save_dir: "experiments/mechanistic/pilots/mechanistic_propagation_v3_512_crop_256_spread_opportunity_q3"

training:
  max_epochs: 5

logger:
  experiment_name: "pilot_mechanistic_propagation_v3_512_crop_256_spread_opportunity_q3"
  tags:
    - "pilot=5_epochs"
