extends: "../ablations/multi_output_spatial_weather_firesize.yaml"

save_dir: "experiments/mechanistic/physical_bp_512_crop_256_spread_opportunity_q3_base"

training:
  gradient_accumulation_steps: 16

data:
  root_dir: "/network/scratch/o/olutayot/nrcan_wildfireriskmapping/data_samples/data_samples_v4_context_512_crop_256"
  batch_size: 4
  num_workers: 4
  input_sources:
    - name: "grid"
      params:
        feature_names_list: ["ignition_grid_human", "ignition_grid_lightning", "fuel_grid", "elevation_grid"]
        targets:
          - name: "bp"
            out_norm: "none"
          - name: "fi"
            out_norm: "log_standard"
          - name: "ros"
            out_norm: "log_standard"
        fuel_feats_encoding: "iROS"
        normalize_fuel_feats_ordinal: false
        transforms_list: []
        augmentation_prob: 0.0
        terrain_derivatives: ["slope", "aspect_sin", "aspect_cos"]
        bp_nodata_as_zero: true

    - name: "spatialized_weather"
      params:
        csv_name: "weather_table_processed.csv"
        feature_names_list:
          - "Temperature"
          - "RelativeHumidity"
          - "Precipitation"
          - "FineFuelMoistureCode"
          - "DuffMoistureCode"
          - "DroughtCode"
          - "InitialSpreadIndex"
          - "BuildupIndex"
          - "FireWeatherIndex"
          - "wind_x"
          - "wind_y"
        fire_weather_zone_id_col: "WeatherZone"
        fire_weather_zone_selection_approach: "mode"
        hex_id_col: "hex_id"
        aggregation: "mean"
        zone_channel_key: "firezones_grid"
        missing_value_strategy: "global_mean"
        include_missing_firezone_mask: false
        shuffle_lut: false
        shuffle_seed: 42
        transforms_list: []
        augmentation_prob: 0.0

    - name: "spatialized_spread_opportunity"
      params:
        csv_name: "spread_opportunity_processed.csv"
        feature_names_list:
          - "NORM_TOTAL_BURN_HOURS_Q10"
          - "NORM_TOTAL_BURN_HOURS_Q50"
          - "NORM_TOTAL_BURN_HOURS_Q90"
          - "SCENARIO_FALLBACK"
        fire_weather_zone_id_col: "GRIDCODE"
        fire_weather_zone_selection_approach: "mode"
        hex_id_col: "hex_id"
        aggregation: "mean"
        zone_channel_key: "firezones_grid"
        missing_value_strategy: "raise"
        include_missing_firezone_mask: false
        shuffle_lut: false
        shuffle_seed: 42
        transforms_list: []
        augmentation_prob: 0.0

data_prep:
  win_h: 512
  win_w: 512
  target_crop_h: 256
  target_crop_w: 256
  overlap_ratio: 0.2
